name: "Unzip all zips"
description: "Unzip all the zip files located in a given directory"
inputs:
  input-dir:
    description: 'Directory that contains zip files'
    required: true
  output-dir:
    description: 'Output directory that will contain all unzipped files'
    required: true
  include-pattern:
    description: 'Remove all files that does not fit this pattern'
    required: false

runs:
  using: "composite"
  steps:
    - name: Create Output dir
      id: create-output-dir
      shell: bash
      run: |
        mkdir -p ${{ inputs.output-dir }}

    - name: unzip all files
      shell: bash
      run: |
        for zip_file in ${{ inputs.input-dir }}/*.zip; do
          if [[ -e "$zip_file" ]]; then
            unzip -o "$zip_file" -d ${{ inputs.output-dir }}
          fi
        done

    - name: Filter Include Pattern
      if: ${{ inputs.include-pattern }} != ''
      shell: bash
      run: |
        find ${{ inputs.output-dir }} -type f ! -name "${{ inputs.include-pattern }}" -exec rm {} \;
        ls ${{ inputs.output-dir }}