name: "Download All Target Comparison Artifacts"
description: "Downloads all the artifacts for all targets needed for run comparison"
inputs:
  gcchash:
    required: true
  token:
    required: true

runs:
  using: "composite"
  steps:
    # Download linux

    - name: Download linux rv32 non-multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-linux-rv32gc-ilp32d-${{ inputs.gcchash }}-non-multilib-report.log
        binary-artifact-name: gcc-linux-rv32gc-ilp32d-${{ inputs.gcchash }}-non-multilib
        github-token: ${{ inputs.token }}

    - name: Download linux rv64gc non-multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-linux-rv64gc-lp64d-${{ inputs.gcchash }}-non-multilib-report.log
        binary-artifact-name: gcc-linux-rv64gc-lp64d-${{ inputs.gcchash }}-non-multilib
        github-token: ${{ inputs.token }}

    - name: Download linux rv32 bitmanip non-multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-linux-rv32gc_zba_zbb_zbc_zbs_zfa-ilp32d-${{ inputs.gcchash }}-non-multilib-report.log
        binary-artifact-name: gcc-linux-rv32gc_zba_zbb_zbc_zbs_zfa-ilp32d-${{ inputs.gcchash }}-non-multilib
        github-token: ${{ inputs.token }}

    - name: Download linux rv64 bitmanip non-multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-linux-rv64gc_zba_zbb_zbc_zbs_zfa-lp64d-${{ inputs.gcchash }}-non-multilib-report.log
        binary-artifact-name: gcc-linux-rv64gc_zba_zbb_zbc_zbs_zfa-lp64d-${{ inputs.gcchash }}-non-multilib
        github-token: ${{ inputs.token }}

    # Newlib

    - name: Download newlib rv32 non-multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-newlib-rv32gc-ilp32d-${{ inputs.gcchash }}-non-multilib-report.log
        binary-artifact-name: gcc-newlib-rv32gc-ilp32d-${{ inputs.gcchash }}-non-multilib
        github-token: ${{ inputs.token }}

    - name: Download newlib rv64gc non-multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-newlib-rv64gc-lp64d-${{ inputs.gcchash }}-non-multilib-report.log
        binary-artifact-name: gcc-newlib-rv64gc-lp64d-${{ inputs.gcchash }}-non-multilib
        github-token: ${{ inputs.token }}

    - name: Download newlib rv32 bitmanip non-multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-newlib-rv32gc_zba_zbb_zbc_zbs_zfa-ilp32d-${{ inputs.gcchash }}-non-multilib-report.log
        binary-artifact-name: gcc-newlib-rv32gc_zba_zbb_zbc_zbs_zfa-ilp32d-${{ inputs.gcchash }}-non-multilib
        github-token: ${{ inputs.token }}

      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-newlib-rv64gc_zba_zbb_zbc_zbs_zfa-lp64d-${{ inputs.gcchash }}-non-multilib-report.log
        binary-artifact-name: gcc-newlib-rv64gc_zba_zbb_zbc_zbs_zfa-lp64d-${{ inputs.gcchash }}-non-multilib
        github-token: ${{ inputs.token }}

    # Multilib
    - name: Download linux multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-linux-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: gcc-linux-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    - name: Download newlib multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-newlib-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: gcc-newlib-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}
