name: "Download Comparison Artifacts"
description: "Downloads artifacts needed for run comparison"
inputs:
  report-artifact-name:
    required: true
  binary-artifact-name:
    required: true
  github-token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Download report from this workflow
      if: ${{ !cancelled() }}
      id: same-workflow-report
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.report-artifact-name }}
        path: ./riscv-gnu-toolchain/current_logs
      continue-on-error: true

    # If an artifact from the same workflow is not found, the conclusion
    # will be success but the outcome will be failure.
    # https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
    - name: Download report from another workflow
      if: ${{ !cancelled() && steps.same-workflow-report.outcome == 'failure' }}
      id: other-workflow-report
      shell: bash
      run: |
        pip install pygithub requests
        cd riscv-gnu-toolchain
        python ./scripts/download_artifact.py -name ${{ inputs.report-artifact-name }} -repo patrick-rivos/gcc-postcommit-ci -token ${{ inputs.github-token }} -outdir current_logs
      continue-on-error: true

    - name: Report failed download
      if: ${{ !cancelled() && steps.same-workflow-report.outcome == 'failure' && steps.other-workflow-report.outcome == 'failure' }}
      id: report-download
      shell: bash
      run: |
        echo "report_download=failure" >> $GITHUB_OUTPUT

    - name: Download binary artifact from this workflow
      if: ${{ !cancelled() && steps.report-download.outputs.report_download == 'failure'}}
      id: same-workflow-binary
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.binary-artifact-name }}
        path: ./riscv-gnu-toolchain/temp
      continue-on-error: true


    - name: Download binary from another workflow
      if: ${{ !cancelled() && steps.report-download.outputs.report_download == 'falure' && steps.same-workflow-binary.outcome == 'failure' }}
      shell: bash
      run: |
        cd riscv-gnu-toolchain
        python ./scripts/download_artifact.py -name ${{ inputs.binary-artifact-name }} -repo patrick-rivos/gcc-postcommit-ci -token ${{ inputs.github-token }} -outdir temp
      continue-on-error: true
