name: "Init and setup gcc"
description: "Initializes and pull gcc with retries"
inputs:
  init:
    description: 'Do (or do not) remove and reclone gcc. Defaults to false'
    required: false
    default: 'false'
  branch:
    description: 'Coordination, release, or master branch to initialize'
    required: false
    default: 'master'

runs:
  using: "composite"
  steps:
      - name: Initialize gcc
        shell: bash
        working-directory: ./riscv-gnu-toolchain
        id: init
        if: ${{ inputs.init == 'true' }}
        run: |
          rm -rf gcc
          git clone https://github.com/gcc-mirror/gcc.git
        continue-on-error: true

      - name: Sleep and retry
        shell: bash
        working-directory: ./riscv-gnu-toolchain
        if: ${{ steps.init.outcome == 'failure' }}
        run: |
          echo "Failed to clone gcc. Retrying in 1 min"
          sleep 60
          git clone https://github.com/gcc-mirror/gcc.git

      - name: Detect unrecognized branches
        shell: bash
        if: ${{ inputs.branch != 'master' && inputs.branch != 'coordination' && inputs.branch != 'release-14' && inputs.branch != 'release-15' }}
        run: |
          echo "inputs.branch found \"${{ inputs.branch }}\""
          exit 1

      - name: Checkout master branch
        shell: bash
        if: ${{ inputs.branch == 'master' }}
        working-directory: ./riscv-gnu-toolchain
        id: pull-master
        run: |
          cd gcc
          git checkout master
          git pull
        continue-on-error: true

      - name: Sleep and retry
        shell: bash
        working-directory: ./riscv-gnu-toolchain
        if: ${{ steps.pull-master.outcome == 'failure' && inputs.branch == 'master' }}
        run: |
          echo "Failed to checkout and pull gcc. Retrying in 1 min"
          sleep 60
          cd gcc
          git checkout master
          git pull

      - name: Checkout coordination branch
        shell: bash
        if: ${{ inputs.branch == 'coordination' }}
        working-directory: ./riscv-gnu-toolchain
        id: pull-coordination
        run: |
          cd gcc
          git config --add remote.origin.fetch "+refs/vendors/riscv/*:refs/remotes/upstream/vendors/riscv/*"
          git fetch
          git checkout upstream/vendors/riscv/heads/gcc-14-with-riscv-opts
        continue-on-error: true

      - name: Sleep and retry
        shell: bash
        working-directory: ./riscv-gnu-toolchain
        if: ${{ steps.pull-coordination.outcome == 'failure' && inputs.branch == 'coordination' }}
        run: |
          echo "Failed to checkout and pull gcc. Retrying in 1 min"
          sleep 60
          cd gcc
          git config --add remote.origin.fetch "+refs/vendors/riscv/*:refs/remotes/upstream/vendors/riscv/*"
          git fetch
          git checkout upstream/vendors/riscv/heads/gcc-14-with-riscv-opts

      - name: Checkout release-14 branch
        shell: bash
        if: ${{ inputs.branch == 'release-14' }}
        working-directory: ./riscv-gnu-toolchain
        id: pull-release-14
        run: |
          cd gcc
          git fetch
          git checkout origin/releases/gcc-14
        continue-on-error: true

      - name: Sleep and retry
        shell: bash
        working-directory: ./riscv-gnu-toolchain
        if: ${{ steps.pull-release-14.outcome == 'failure' && inputs.branch == 'release-14' }}
        run: |
          echo "Failed to checkout and pull gcc. Retrying in 1 min"
          sleep 60
          cd gcc
          git fetch
          git checkout origin/releases/gcc-14

      - name: Checkout release-15 branch
        shell: bash
        if: ${{ inputs.branch == 'release-15' }}
        working-directory: ./riscv-gnu-toolchain
        id: pull-release-15
        run: |
          cd gcc
          git fetch
          git checkout origin/releases/gcc-15
        continue-on-error: true

      - name: Sleep and retry
        shell: bash
        working-directory: ./riscv-gnu-toolchain
        if: ${{ steps.pull-release-15.outcome == 'failure' && inputs.branch == 'release-15' }}
        run: |
          echo "Failed to checkout and pull gcc. Retrying in 1 min"
          sleep 60
          cd gcc
          git fetch
          git checkout origin/releases/gcc-15
