name: "Download All Weekly Target Comparison Artifacts"
description: "Downloads all the artifacts for all targets needed for run comparison"
inputs:
  gcchash:
    required: true
  token:
    required: true
  prefix:
    required: false

runs:
  using: "composite"
  steps:
    # Download linux

    - name: Download linux rv32 zve64d
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'zve_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv32gcv_zve64d-ilp32d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv32gcv_zve64d-ilp32d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    - name: Download linux rv64 zve64d
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'zve_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zve64d-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zve64d-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    # Download rv64 zvl builds.

    - name: Download linux rv64-1024b
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'rv64_zvl_' || inputs.prefix == 'rv64_zvl_lmul2_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zvl1024b-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zvl1024b-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    - name: Download linux rv64-512b
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'rv64_zvl_' || inputs.prefix == 'rv64_zvl_lmul2_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zvl512b-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zvl512b-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    - name: Download linux rv64-256b
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'rv64_zvl_' || inputs.prefix == 'rv64_zvl_lmul2_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zvl256b-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zvl256b-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    # only have 128b for lmul2 runs
    - name: Download linux rv64-128b
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'rv64_zvl_lmul2_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zvl128b-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zvl128b-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    # Download rv32 zvl builds.

    - name: Download linux rv32-1024b
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'rv32_zvl_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv32gcv_zvl1024b-ilp32d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv32gcv_zvl1024b-ilp32d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    - name: Download linux rv32-512b
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'rv32_zvl_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv32gcv_zvl512b-ilp32d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv32gcv_zvl512b-ilp32d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    - name: Download linux rv32-256b
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'rv32_zvl_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv32gcv_zvl256b-ilp32d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv32gcv_zvl256b-ilp32d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    # Download rv32/64 binutils builds.

    - name: Download linux rv64-binutils
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'binutils_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gc-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gc-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    - name: Download linux rv32-binutils
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'binutils_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv32gc-ilp32d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv32gc-ilp32d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    - name: Download newlib rv64-binutils
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'binutils_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-newlib-rv64gc-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-newlib-rv64gc-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    - name: Download newlib rv32-binutils
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'binutils_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-newlib-rv32gc-ilp32d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-newlib-rv32gc-ilp32d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}

    # Download with checking builds

    - name: Download linux rv64 with checking
      uses: ./.github/actions/common/download-comparison-artifacts
      if: ${{ inputs.prefix == 'checking_' }}
      with:
        report-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zicond-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: ${{ inputs.prefix }}gcc-linux-rv64gcv_zicond-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}
