name: "Download All Buid Log Artifacts"
description: "Downloads all the build log artifacts for a given hash. Only use this action if the given gcchash is not built in the current run"
inputs:
  gcchash:
    required: true
    description: 'GCC Hash of the artifact'
  github-token:
    required: true
  prefix:
    required: false
  output-dir:
    required: true
    description: 'Absolute Path to the artifact directory'

runs:
  using: "composite"
  steps:
    - name: prereqs
      shell: bash
      run: |
        mkdir -p ${{ inputs.output-dir }}

    # Download linux
    - name: Download linux rv32 non-multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}linux-rv32gc-ilp32d-${{ inputs.gcchash }}-non-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    - name: Download linux rv64gc non-multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}linux-rv64gc-lp64d-${{ inputs.gcchash }}-non-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    - name: Download linux rv32 bitmanip non-multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}linux-rv32gc_zba_zbb_zbc_zbs-ilp32d-${{ inputs.gcchash }}-non-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    - name: Download linux rv64 bitmanip non-multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}linux-rv64gc_zba_zbb_zbc_zbs-lp64d-${{ inputs.gcchash }}-non-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    # Newlib

    - name: Download newlib rv32 non-multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}newlib-rv32gc-ilp32d-${{ inputs.gcchash }}-non-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    - name: Download newlib rv64gc non-multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}newlib-rv64gc-lp64d-${{ inputs.gcchash }}-non-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    - name: Download newlib rv32 bitmanip non-multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}newlib-rv32gc_zba_zbb_zbc_zbs-ilp32d-${{ inputs.gcchash }}-non-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    - name: Download newlib rv64 bitmanip non-multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}newlib-rv64gc_zba_zbb_zbc_zbs-lp64d-${{ inputs.gcchash }}-non-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    # Multilib
    - name: Download linux multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}linux-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    - name: Download newlib multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}newlib-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    - name: Download newlib uc multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}newlib-rv64imc-lp64d-${{ inputs.gcchash }}-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    - name: Download newlib uc bitmanip multilib
      uses: ./.github/actions/common/download-build-log-artifact
      with:
        build-artifact-name: ${{ inputs.prefix }}newlib-rv64imc_zba_zbb_zbc_zbs-lp64d-${{ inputs.gcchash }}-multilib-build-log
        github-token: ${{ inputs.github-token }}
        output-dir: ${{ inputs.output-dir }}

    - name: Print downloaded artifacts
      shell: bash
      run: |
        cd riscv-gnu-toolchain
        ls ${{ inputs.output-dir }}
