#!/bin/bash
../configure --prefix=$(pwd) --with-multilib-generator="rv32imac_zba_zbb_zbc-ilp32--;rv32imc_zba_zbb_zbc-ilp32--;rv32imc_zba_zbb_zbc_zicsr_zifencei-ilp32--;rv32imc_zba_zbb_zbc_zbs_zicsr_zifencei-ilp32--"

