#!/bin/bash
../configure --prefix=$(pwd) --with-multilib-generator="rv64imac_zba_zbb_zbc-lp64--;rv64imc_zba_zbb_zbc-lp64--;rv64imc_zba_zbb_zbc_zicsr_zifencei-lp64--;rv64imc_zba_zbb_zbc_zbs_zicsr_zifencei-lp64--"

