name: Run-Weekly-rv32-zvl

# rv32gcv_zvl variants

on:
  schedule:
    # Run at 4:00pm on Mondays
    - cron: 0 16 * * 1
  workflow_dispatch:
    branches:
      - main

jobs:
  init-submodules:
    uses: ./.github/workflows/init-submodules.yaml
    with:
      # Add new prefixes to /dashboard/getdata.py in download_summaries()
      prefix: 'rv32_zvl_'

  # Will take a long time to complete (4 targets)
  zvl-variants-self-hosted:
    needs: [init-submodules]
    strategy:
      fail-fast: false
      matrix:
        mode: [linux]
        target: [
          # rv32gcv_zvl128b-ilp32d,
          # rv32gcv_zvl256b-ilp32d,
          # rv32gcv_zvl512b-ilp32d,
          rv32gcv_zvl1024b-ilp32d,
        ]
        multilib: [multilib]
    uses: ./.github/workflows/build-test.yaml
    with:
      mode: ${{ matrix.mode }}
      target: ${{ matrix.target }}
      gcchash: ${{ needs.init-submodules.outputs.gcchash }}
      multilib: ${{ matrix.multilib }}
      multitarget: ${{ github.event.inputs.multi_target }}
      run_on_self_hosted: true
      prefix: 'rv32_zvl_'

  # TODO: Generate a summary issue with no baseline
  summarize:
    if: "!cancelled()" # Generate github issues even when some (or all) targets fail to build
    needs: [init-submodules, zvl-variants-self-hosted]
    permissions:
      issues: write
    uses: ./.github/workflows/generate-summary.yaml
    with:
      gcchash: ${{ needs.init-submodules.outputs.gcchash }}
      issue_num: ${{ github.event.inputs.issue_num }}
      issue_hash_prefix: Testsuite rv32gcv-zvl Status
      prefix: 'rv32_zvl_'
