name: Run-Weekly-gcv-zve

# rv{64/32}gcv_zve variants

on:
  schedule:
    # Run at 4:00pm
    - cron: 0 16 * * *
  workflow_dispatch:
    branches:
      - main

jobs:
  init-submodules:
    uses: ./.github/workflows/init-submodules.yaml

  # Will take a long time to complete (4 targets)
  zvl-variants-self-hosted:
    needs: [init-submodules]
    strategy:
      fail-fast: false
      matrix:
        mode: [linux]
        target: [
          rv32gcv_zve32f-ilp32d,
          rv32gcv_zve64d-ilp32d,
          rv64gcv_zve32f-lp64d,
          rv64gcv_zve64d-lp64d,
        ]
        multilib: [non-multilib]
    uses: ./.github/workflows/build-test.yaml
    with:
      mode: ${{ matrix.mode }}
      target: ${{ matrix.target }}
      gcchash: ${{ needs.init-submodules.outputs.gcchash }}
      multilib: ${{ matrix.multilib }}
      multitarget: ${{ github.event.inputs.multi_target }}
      run_on_self_hosted: true

  # TODO: Generate a summary issue with no baseline
