name: "Test RVV Intrinsics"

on:
  workflow_call:
    inputs:
      gcchash:
        required: true
        type: string

jobs:
  rvv-intrinsic-testing:
    runs-on: self-hosted
    environment: production
    steps:
      - name: 'Cleanup build folder'
        working-directory: ./
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env
        with:
          free_up_space: false

      - name: Restore submodules from cache
        uses: actions/download-artifact@v3
        with:
          name: gcc-sources-${{ inputs.gcchash }}
          path: riscv-gnu-toolchain

      - name: Restore submodules
        working-directory: riscv-gnu-toolchain
        run: |
          rm -rf .git binutils dejagnu gcc gdb glibc newlib qemu
          unzip cache.zip
          rm -rf cache.zip

      - name: Print gcc hash
        working-directory: riscv-gnu-toolchain
        run: |
          cd gcc
          git rev-parse HEAD

      - name: Install dependencies
        working-directory: riscv-gnu-toolchain
        run: sudo ./.github/setup-apt.sh

      - name: Clone rvv-intrinsic-doc
        run: |
          git submodule update --init rvv-intrinsic-doc

      - name: Make check-gcc
        run: |
          cd rvv-intrinsic-doc
          make -C rvv-intrinsic-generator report-gnu GNU_TOOLCHAIN_DIR=$(pwd)/../riscv-gnu-toolchain || true

      - name: Print gcc logs
        run: |
          cat riscv-gnu-toolchain/build-gcc-newlib-stage2/gcc/testsuite/gcc/gcc.log

      - name: Print g++ logs
        run: |
          cat riscv-gnu-toolchain/build-gcc-newlib-stage2/gcc/testsuite/g++/g++.log

      - name: Check gcc result
        run: |
          tail -n 17 riscv-gnu-toolchain/build-gcc-newlib-stage2/gcc/testsuite/gcc/gcc.log

      - name: Check g++ result
        run: |
          tail -n 27 riscv-gnu-toolchain/build-gcc-newlib-stage2/gcc/testsuite/g++/g++.log

      - name: Zip logs
        run: |
          mkdir logs
          mv riscv-gnu-toolchain/build-gcc-newlib-stage2/gcc/testsuite/gcc/gcc.log logs
          mv riscv-gnu-toolchain/build-gcc-newlib-stage2/gcc/testsuite/g++/g++.log logs
          zip -r rvv-intrinsic-testing-logs.zip logs

      - name: Upload logs artifact
        uses: actions/upload-artifact@v3
        with:
          name: rvv-intrinsic-testing-logs
          path: |
            rvv-intrinsic-testing-logs.zip
          retention-days: 90
